CREATE TABLE user (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
edad INT NOT NULL,
email VARCHAR(100) NOT NULL,
PRIMARY KEY (id)
);

INSERT INTO user (name, edad, email)
VALUES ('Oscar', 25, 'oscar@gmail.com');
INSERT INTO user (name, edad, email)
VALUES ('Layla', 15, 'layla@gmail.com');
INSERT INTO user (name, edad, email)
VALUES ('Nicolas', 36, 'nico@gmail.com');
INSERT INTO user (name, edad, email)
VALUES ('Chanchito', 7, 'oscar@gmail.com');

SELECT * FROM user;
SELECT * FROM user LIMIT 1;		#LIMITA LA BÚSQUEDA A LA PRIMER COINCIDENCIA 
SELECT * FROM user WHERE edad > 15;		#MUESTRA LOS REGISTROS CON EDAD MAYOR A 15
SELECT * FROM user WHERE edad >= 15; 	#MUESTRA LOS REGISTROS CON EDAD MAYOR O IGUAL A 15
SELECT * FROM user WHERE edad >20 AND email = 'nico@gmail.com';		#MUESTRA LOS REGISTROS CON EDAD MAYOR A 20 Y QUE TENGAN EL CORREO ESPECIFICADO 
SELECT * FROM user WHERE edad >20 OR email = 'layla@gmail.com';		#MUESTRA LOS REGISTROS CON EDAD MAYOR A 20 O QUE TENGAN EL CORREO ESPECIFICADO
SELECT * FROM user WHERE email != 'layla@gmail.com';	#MUESTRA LOS REGISTROS QUE TENGAN UN CORREO DISTINTO AL ESPECIFICADO
SELECT * FROM user WHERE edad BETWEEN 15 AND 30; 	#MUESTRA TODOS LOS REGISTROS QUE TENGAN EDAD ENTRE 15 Y 30
SELECT * FROM user WHERE email LIKE '%gmail%';	#MUESTRA LOS REGISTROS QUE EN EMAIL CONTENGA LOS CARACTERES ESPECIFICADOS ENTRE LOS SIGNOS DE PORCENTAJE
SELECT * FROM user WHERE email LIKE '%gmail';	#MUESTRA LOS REGISTROS QUE TERMINEN CON 'gmail' EN EL CAMPO DE EMAIL
SELECT * FROM user WHERE email LIKE 'oscar%';	#MUESTRA LOS REGISTROS QUE EMPIEZEN CON 'oscar' EN EL CAMPO DE EMAIL

SELECT * FROM USER ORDER BY edad ASC;	#ORDENA LOS DATOS POR SU EDAD EN ORDEN ASCENDENTE (DE MENOR A MAYOR)
SELECT * FROM USER ORDER BY edad DESC;	#ORDENA LOS DATOS POR SU EDAD EN ORDEN DESCENDENTE (DE MAYOR A MENOR)

SELECT MAX(edad) AS MAYOR FROM user;	#BUSCA EL REGISTRO CON MAYOR EDAD Y LE DA EL SOBRENOMBRE DE MAYOR
SELECT MIN(edad) AS MENOR FROM user;	#BUSCA EL REGISTRO CON MENOR EDAD Y LE DA EL SOBRENOMBRE DE MENOR

SELECT id, name FROM user;		#MUESTRA UNICAMENTE LAS COLUMNAS id y name DE LA TABLA USUARIO
SELECT id AS IDENTIFIER, name AS NOMBRE FROM user;	#LE ASIGNA UN ALIAS A LAS COLUMNAS ESPECIFICADAS Y SE VISUALIZAN LAS COLUMNAS CON EL ALIAS

